version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: master
  - package-ecosystem: terraform
    directory: /.ci/terraform
    schedule:
      interval: weekly
    target-branch: master
